/**
 * Game-session-specific token helpers.
 *
 * Authentication tokens (refresh / access / verification / reset) are
 * generated by `src/server/auth/tokens.ts`; this file handles only the
 * remaining session-side token: the eight-digit accept code that one
 * player shares with another to invite them into a game.
 *
 * The accept code's lower entropy is acceptable because (a) it is
 * single-use and consumed atomically on first redemption, and (b) the
 * server limits the attack surface to one correct guess per session.
 */

import { randomInt } from "node:crypto";

/**
 * Generate a fresh eight-digit accept code, zero-padded.
 *
 * `randomInt(0, 100_000_000)` returns a uniformly distributed integer
 * in `[0, 1e8)` so every eight-digit string has the same probability
 * of being generated. The padding ensures we never silently produce a
 * shorter code.
 */
export function generateAcceptToken(): string {
  return randomInt(0, 100_000_000).toString().padStart(8, "0");
}

// Re-export the cryptographic-hash helper from the auth tokens module.
// Game session code uses it to hash the accept token before storage.
export { hashToken } from "./auth/tokens";
